baseURL = 'https://chenxiangworld.com/'
languageCode = 'zh-cn'
title = '在中关村写诗'
theme = 'paper'

[params]
  color = 'linen'
  avatar = 'https://chenxiangworld.com/chenxiang.jpg'
  name = '陈翔'
  bio = '记录写过的一些诗'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 1

