baseURL = 'https://chenxiangworld.com/'
title = '在中关村写诗'
theme = 'paper'

defaultContentLanguage = 'zh'

[languages]
  [languages.zh]
    languageCode = 'zh-cn'
    languageName = '中文'
    weight = 1
    contentDir = 'content/zh'
    [languages.zh.params]
      color = 'linen'
      avatar = 'https://chenxiangworld.com/avatar.jpg'
      name = '陈翔'
      bio = '记录写过的一些诗'

  [languages.en]
    languageCode = 'en'
    languageName = "EN"
    weight = 2
    title = "Writing Poems in Beijing"
    contentDir = 'content/en'
    [languages.en.params]
      color = 'linen'
      avatar = 'https://chenxiangworld.com/avatar.jpg'
      name = 'Sean Chen'
      bio = "A record of some poems I've written."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions.typographer]
      disable = true

[params]
  color = 'linen'
